### ISSUE TITLE
FirestoreListenerService 구현

### ISSUE THREAD

**Issue by chansooo** [boostcampwm-2022/iOS02-Trinap#109]
# 요약
FirestoreListenerService 구현

# 상세 설명
FirestoreListenerService 구현

# 체크리스트
- [ ] startObserve 메소드 구현
- [ ] stopObserve 메소드 구현
- [ ] post 메소드 구현
- [ ] update 메소드 구현
- [ ] fetch 메소드

**Comment by yy0867** [comment]
#108 에서 처리하였습니다.
