### ISSUE TITLE
FetchPhotographerListUseCase

### ISSUE THREAD

**Issue by ByeongjooYoo** [boostcampwm-2022/iOS02-Trinap#81]
# 요약
FetchPhotographerListUseCase 구현
# 상세 설명
FetchPhotographerListUseCase Protocol 및 DefaultFetchPhotographerListUseCase 구현
# 체크리스트
- [x] FetchPhotographerListUseCase Protocol 선언
- [x] 작가 목록 조회 기능
- [ ] 댓글 평점 평균 계산 기능
- [x] DefaultFetchPhotographerListUseCase 구현

**Comment by chansooo** [comment]
댓글 평점 평균 내는 부분 #80 으로 이관
